var model = {
  "backgroundSize": "1.8",
  "more2": "00",
  "argsSortState": "d",
  "tagPositionLeft": "80%",
  "argsList": [{ "prefixName": "", "color": "", "name": "产品名称", "inline": "h", "value": "name", "display": "s" }, { "prefixName": "型号：", "color": "", "name": "产品型号", "inline": "h", "value": "prodtype", "display": "h" }, { "prefixName": "价格：", "color": "", "name": "产品价格", "inline": "h", "value": "price", "display": "s" }, { "prefixName": "原价：", "color": "", "name": "市场价格", "inline": "h", "value": "marketprice", "display": "h" }],
  "tstyles": { "color": { "titleText": { "color": "#fff" }, "icon-pageNext:before": { "color": "#fff" }, "pagePrev": { "border-color": "#fff" }, "titleMoreIcon": { "color": "#fff" }, "pageNext": { "border-color": "#fff" }, "titleTextIcon": { "background-color": "#fff" }, "icon-pagePrev:before": { "color": "#fff" } } },
  "backgroundPositionTop": "100%",
  "type": "isNew",
  "jumpType": "d",
  "moreImg": "",
  "sortField": "sort",
  "tagPosition": "0% 100%",
  "backgroundPosition": "100% 100%",
  "swiperNumber": "1",
  "argsShow": "s",
  "textAlign": "center",
  "moreText": "更多",
  "whiteSpace": "paramWrap",
  "showMore": "yes",
  "listType": "f",
  "pageSize": "4",
  "themeState": "d",
  "styles": {},
  "autoplay": "0",
  "swiperButton": "blue",
  "category": "Category_00000000000000000023193",
  "backgroundPositionLeft": "100%",
  "effect": "slide",
  "proCompose": "00",
  "tagName": "",
  "background": "",
  "pro": { "borderStyle": "solid", "borderColor": "#000", "borderWidth": "0.044rem", "borderState": "d", "paramName": { "display": "block" } },
  "target": [],
  "sortType": "desc",
  "paginationType": "h",
  "pagination": "no",
  "tagColor": "#999",
  "tagPositionTop": "0%",
  "scrollLoading": "01"
}
